apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: c3RhZ2V1c2Vy
  MONGO_INITDB_ROOT_PASSWORD: c2VuaGFzYWdl


---

apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
type: Opaque
data:
  docker-server: <registry-name>
  docker-username: <username>
  docker-password: <password>
  docker-email: <user@email.com>